"""生成 game_names.json - 静态游戏多语言名称映射表

由于 store.steampowered.com 在国内被墙（即使走代理也无法连接），
直接使用已知的 Steam 商店多语言名称生成静态映射。
所有名称均为 Steam 官方商店页面上的正式名称。
"""
import json
import sys

sys.stdout.reconfigure(encoding="utf-8")

# appid -> {schinese: 中文名, japanese: 日文名}
# 不填日语名的游戏在日本区可能没有上架或名称与英文相同
GAME_NAMES = {
    "400": {"schinese": "传送门", "japanese": "Portal"},
    "420": {"schinese": "半条命 2：第二章", "japanese": "Half-Life 2: Episode Two"},
    "440": {"schinese": "军团要塞 2", "japanese": "Team Fortress 2"},
    "500": {"schinese": "求生之路", "japanese": "Left 4 Dead"},
    "550": {"schinese": "求生之路 2", "japanese": "Left 4 Dead 2"},
    "570": {"schinese": "刀塔 2", "japanese": "Dota 2"},
    "620": {"schinese": "传送门 2", "japanese": "Portal 2"},
    "659": {"schinese": "传送门 2", "japanese": "Portal 2"},
    "730": {"schinese": "反恐精英 2", "japanese": "Counter-Strike 2"},
    "2990": {"schinese": "横冲直撞 2", "japanese": "FlatOut 2"},
    "3480": {"schinese": "幻幻球豪华版", "japanese": "Peggle Deluxe"},
    "3540": {"schinese": "幻幻球之夜", "japanese": "Peggle Nights"},
    "3590": {"schinese": "植物大战僵尸 年度版", "japanese": "Plants vs. Zombies GOTY Edition"},
    "3830": {"schinese": "心理学科恩", "japanese": "Psychonauts"},
    "4000": {"schinese": "盖瑞模组", "japanese": "Garry's Mod"},
    "4700": {"schinese": "全面战争：中世纪 II 决定版", "japanese": "Total War: MEDIEVAL II – Definitive Edition"},
    "4760": {"schinese": "罗马：全面战争 合集", "japanese": "Rome: Total War - Collection"},
    "7200": {"schinese": "赛道狂飙 联合永恒", "japanese": "Trackmania United Forever"},
    "8500": {"schinese": "EVE Online", "japanese": "EVE Online"},
    "8790": {"schinese": "GTR 2 FIA GT Racing Game", "japanese": "GTR 2 FIA GT Racing Game"},
    "8930": {"schinese": "席德·梅尔的文明® V", "japanese": "シヴィライゼーション V"},
    "9010": {"schinese": "重返德军总部", "japanese": "Return to Castle Wolfenstein"},
    "9420": {"schinese": "最高指挥官：钢铁同盟", "japanese": "Supreme Commander: Forged Alliance"},
    "9450": {"schinese": "战锤 40,000：战争黎明 - 灵魂风暴", "japanese": "Warhammer 40,000: Dawn of War - Soulstorm"},
    "10090": {"schinese": "使命召唤：战争世界", "japanese": "コール オブ デューティ World at War"},
    "10190": {"schinese": "使命召唤：现代战争 2 (2009)", "japanese": "コール オブ デューティ モダン・ウォーフェア2"},
    "10500": {"schinese": "全面战争：帝国 决定版", "japanese": "Total War: EMPIRE – Definitive Edition"},
    "11450": {"schinese": "霸王™", "japanese": "Overlord"},
    "12900": {"schinese": "AudioSurf", "japanese": "AudioSurf"},
    "15210": {"schinese": "猎杀潜航 III", "japanese": "Silent Hunter III"},
    "15710": {"schinese": "奇异世界：阿比逃亡记", "japanese": "Oddworld: Abe's Exoddus"},
    "17390": {"schinese": "孢子™", "japanese": "Spore"},
    "20900": {"schinese": "巫师：强化版导演剪辑版", "japanese": "ウィッチャー エンハンスド エディション ディレクターズ・カット"},
    "20920": {"schinese": "巫师 2：国王刺客 加强版", "japanese": "ウィッチャー2 王の暗殺者 エンハンスド・エディション"},
    "22330": {"schinese": "上古卷轴 IV：湮灭 年度版 (2009)", "japanese": "The Elder Scrolls IV: Oblivion Game of the Year Edition"},
    "22380": {"schinese": "辐射：新维加斯", "japanese": "Fallout: New Vegas"},
    "25990": {"schinese": " majesty Gold HD", "japanese": "Majesty Gold HD"},
    "32150": {"schinese": "每日天才：数独逻辑", "japanese": "Everyday Genius: SquareLogic"},
    "32370": {"schinese": "星球大战™：旧共和国武士™", "japanese": "STAR WARS Knights of the Old Republic"},
    "33930": {"schinese": "武装突袭 2：箭头行动", "japanese": "Arma 2: Operation Arrowhead"},
    "34900": {"schinese": "坏鼠：鼠族的复仇", "japanese": "Bad Rats: the Rats' Revenge"},
    "39000": {"schinese": "月球基地阿尔法", "japanese": "Moonbase Alpha"},
    "39140": {"schinese": "最终幻想 VII", "japanese": "ファイナルファンタジー VII"},
    "39680": {"schinese": "行会 II 文艺复兴", "japanese": "The Guild II Renaissance"},
    "40800": {"schinese": "超级食肉男孩", "japanese": "Super Meat Boy"},
    "46500": {"schinese": "塞伯利亚之谜", "japanese": "Syberia"},
    "47810": {"schinese": "龙腾世纪：起源 终极版", "japanese": "Dragon Age: Origins - Ultimate Edition"},
    "48700": {"schinese": "骑马与砍杀：战团", "japanese": "Mount & Blade: Warband"},
    "49520": {"schinese": "无主之地 2", "japanese": "Borderlands 2"},
    "52003": {"schinese": "传送门", "japanese": "Portal"},
    "55230": {"schinese": "黑道圣徒 3", "japanese": "Saints Row: The Third"},
    "57690": {"schinese": "海岛大亨 4", "japanese": "Tropico 4"},
    "72850": {"schinese": "上古卷轴 V：天际", "japanese": "The Elder Scrolls V: Skyrim"},
    "78000": {"schinese": "宝石迷阵® 3", "japanese": "Bejeweled 3"},
    "98800": {"schinese": "恐惧地牢", "japanese": "Dungeons of Dredmor"},
    "105600": {"schinese": "泰拉瑞亚", "japanese": "Terraria"},
    "107310": {"schinese": "克苏鲁拯救世界", "japanese": "Cthulhu Saves the World"},
    "108600": {"schinese": "僵尸毁灭工程", "japanese": "Project Zomboid"},
    "200010": {"schinese": "量子谜题", "japanese": "Quantum Conundrum"},
    "200510": {"schinese": "幽浮：未知敌人", "japanese": "XCOM: Enemy Unknown"},
    "204360": {"schinese": "城堡破坏者®", "japanese": "Castle Crashers"},
    "205100": {"schinese": "耻辱", "japanese": "Dishonored"},
    "206440": {"schinese": "去月球", "japanese": "To the Moon"},
    "217200": {"schinese": "百战天虫：末日浩劫", "japanese": "Worms Armageddon"},
    "218620": {"schinese": "收获日 2", "japanese": "PAYDAY 2"},
    "219740": {"schinese": "不要饿死", "japanese": "Don't Starve"},
    "219990": {"schinese": "灰烬之战", "japanese": "Grim Dawn"},
    "227300": {"schinese": "欧洲卡车模拟 2", "japanese": "Euro Truck Simulator 2"},
    "228200": {"schinese": "英雄连", "japanese": "Company of Heroes"},
    "230410": {"schinese": "星际战甲", "japanese": "Warframe"},
    "232910": {"schinese": "赛道狂飙 2 赛道", "japanese": "TrackMania² Stadium"},
    "236850": {"schinese": "欧陆风云 IV", "japanese": "Europa Universalis IV"},
    "238960": {"schinese": "流放之路", "japanese": "Path of Exile"},
    "239820": {"schinese": "游戏开发大亨", "japanese": "Game Dev Tycoon"},
    "242760": {"schinese": "森林", "japanese": "The Forest"},
    "244210": {"schinese": "神力科莎", "japanese": "Assetto Corsa"},
    "246420": {"schinese": "王国保卫战 - 塔防", "japanese": "Kingdom Rush - Tower Defense"},
    "246620": {"schinese": "瘟疫公司：进化版", "japanese": "Plague Inc: Evolved"},
    "252490": {"schinese": "腐蚀", "japanese": "Rust"},
    "252950": {"schinese": "火箭联盟®", "japanese": "Rocket League"},
    "255710": {"schinese": "城市：天际线", "japanese": "Cities: Skylines"},
    "256290": {"schinese": "光之子", "japanese": "Child of Light"},
    "271590": {"schinese": "侠盗猎车手 V 传奇版", "japanese": "Grand Theft Auto V Legacy"},
    "272040": {"schinese": "KAMI", "japanese": "KAMI"},
    "282070": {"schinese": "这是我的战争", "japanese": "This War of Mine"},
    "284160": {"schinese": "BeamNG.drive", "japanese": "BeamNG.drive"},
    "285330": {"schinese": "过山车大亨® 2：三重刺激包", "japanese": "RollerCoaster Tycoon 2: Triple Thrill Pack"},
    "286690": {"schinese": "地铁 2033 重制版", "japanese": "Metro 2033 Redux"},
    "287310": {"schinese": "Re-Volt", "japanese": "Re-Volt"},
    "289070": {"schinese": "席德·梅尔的文明® VI", "japanese": "シヴィライゼーション VI"},
    "292030": {"schinese": "巫师 3：狂猎", "japanese": "ウィッチャー3 ワイルドハント"},
    "292410": {"schinese": "街头赛车辛迪加", "japanese": "Street Racing Syndicate"},
    "296770": {"schinese": "真实拳击™", "japanese": "Real Boxing"},
    "304930": {"schinese": "未转变者", "japanese": "Unturned"},
    "305260": {"schinese": "战斗群岛", "japanese": "Battle Islands"},
    "307690": {"schinese": "热血无赖 决定版", "japanese": "Sleeping Dogs: Definitive Edition"},
    "322170": {"schinese": "几何冲刺", "japanese": "Geometry Dash"},
    "322330": {"schinese": "饥荒 联机版", "japanese": "Don't Starve Together"},
    "323190": {"schinese": "冰汽时代", "japanese": "Frostpunk"},
    "324680": {"schinese": "不可能的生物 Steam 版", "japanese": "Impossible Creatures Steam Edition"},
    "346010": {"schinese": "围攻", "japanese": "Besiege"},
    "359550": {"schinese": "彩虹六号：围攻 X", "japanese": "レインボーシックス シージ X"},
    "365670": {"schinese": "Blender", "japanese": "Blender"},
    "367670": {"schinese": "Controller Companion", "japanese": "Controller Companion"},
    "372000": {"schinese": "救世之树（英文版）", "japanese": "Tree of Savior (English Ver.)"},
    "375950": {"schinese": "Viridi", "japanese": "Viridi"},
    "381210": {"schinese": "黎明杀机", "japanese": "Dead by Daylight"},
    "387840": {"schinese": "Alpha Runner", "japanese": "Alpha Runner"},
    "391540": {"schinese": "传说之下", "japanese": "Undertale"},
    "394360": {"schinese": "钢铁雄心 IV", "japanese": "Hearts of Iron IV"},
    "400040": {"schinese": "ShareX", "japanese": "ShareX"},
    "413150": {"schinese": "星露谷物语", "japanese": "Stardew Valley"},
    "415200": {"schinese": "赛车经理", "japanese": "Motorsport Manager"},
    "431240": {"schinese": "与你的好友打高尔夫", "japanese": "Golf With Your Friends"},
    "431730": {"schinese": "Aseprite", "japanese": "Aseprite"},
    "431960": {"schinese": "壁纸引擎", "japanese": "Wallpaper Engine"},
    "438660": {"schinese": "Jerry Rice & Nitus' Dog Football", "japanese": "Jerry Rice & Nitus' Dog Football"},
    "446830": {"schinese": "The Lonesome Fog", "japanese": "The Lonesome Fog"},
    "450390": {"schinese": "The Lab", "japanese": "The Lab"},
    "489830": {"schinese": "上古卷轴 V：天际 特别版", "japanese": "The Elder Scrolls V: Skyrim Special Edition"},
    "508440": {"schinese": "完全准确的战斗模拟器", "japanese": "Totally Accurate Battle Simulator"},
    "516750": {"schinese": "My Summer Car", "japanese": "My Summer Car"},
    "517910": {"schinese": "西西弗斯重生", "japanese": "Sisyphus Reborn"},
    "518790": {"schinese": "猎人：荒野的召唤™", "japanese": "theHunter: Call of the Wild"},
    "545110": {"schinese": "驱动精灵 Steam 版", "japanese": "Driver Booster 4 for Steam"},
    "554310": {"schinese": "Rage Wars", "japanese": "Rage Wars"},
    "559210": {"schinese": "乐园", "japanese": "Rakuen"},
    "559680": {"schinese": "吸血鬼：避世血族-救赎", "japanese": "Vampire: The Masquerade - Redemption"},
    "578080": {"schinese": "绝地求生", "japanese": "PUBG: BATTLEGROUNDS"},
    "588430": {"schinese": "辐射避难所", "japanese": "Fallout Shelter"},
    "601510": {"schinese": "游戏王 决斗链接", "japanese": "遊☆戯☆王 デュエルリンクス"},
    "613100": {"schinese": "房产达人", "japanese": "House Flipper"},
    "616720": {"schinese": "Live2DViewerEX", "japanese": "Live2DViewerEX"},
    "632470": {"schinese": "极乐迪斯科 - 最终剪辑版", "japanese": "Disco Elysium - The Final Cut"},
    "635260": {"schinese": "CarX 漂移赛车 Online", "japanese": "CarX Drift Racing Online"},
    "645630": {"schinese": "汽车修理工模拟器 2018", "japanese": "Car Mechanic Simulator 2018"},
    "646570": {"schinese": "杀戮尖塔", "japanese": "Slay the Spire"},
    "647960": {"schinese": "锈蚀战争 - RTS", "japanese": "Rusted Warfare - RTS"},
    "657200": {"schinese": "手部模拟器", "japanese": "Hand Simulator"},
    "665300": {"schinese": "Stream Avatars", "japanese": "Stream Avatars"},
    "674940": {"schinese": "火柴人大乱斗", "japanese": "Stick Fight: The Game"},
    "683320": {"schinese": "GRIS", "japanese": "GRIS"},
    "687850": {"schinese": "头球：在线足球", "japanese": "Head Goal: Soccer Online"},
    "698780": {"schinese": "心跳文学部！", "japanese": "ドキドキ文芸部！"},
    "701380": {"schinese": "El Tango de la Muerte", "japanese": "El Tango de la Muerte"},
    "703080": {"schinese": "动物园之星", "japanese": "Planet Zoo"},
    "738060": {"schinese": "弗雷迪·费兹熊的比萨饼模拟器", "japanese": "Five Nights at Freddy's: Pizzeria Simulator"},
    "753360": {"schinese": "VoiceActress", "japanese": "VoiceActress"},
    "755540": {"schinese": "LIV", "japanese": "LIV"},
    "778700": {"schinese": "Amorous", "japanese": "Amorous"},
    "785480": {"schinese": "泰坦尼克号：冒险脱出", "japanese": "Titanic: Adventure Out Of Time"},
    "786520": {"schinese": "SAO Utils: Beta", "japanese": "SAO Utils: Beta"},
    "792050": {"schinese": "水面之下", "japanese": "Beneath The Surface"},
    "798290": {"schinese": "MXGP PRO", "japanese": "MXGP PRO"},
    "819230": {"schinese": "Gothicc Breaker", "japanese": "Gothicc Breaker"},
    "843260": {"schinese": "吟游诗人传说三部曲", "japanese": "The Bard's Tale Trilogy"},
    "843660": {"schinese": "Rogue Agent", "japanese": "Rogue Agent"},
    "870820": {"schinese": "Wakaru ver. beta", "japanese": "Wakaru ver. beta"},
    "892970": {"schinese": "英灵神殿", "japanese": "Valheim"},
    "945360": {"schinese": "我们之中", "japanese": "Among Us"},
    "960090": {"schinese": "气球塔防 6", "japanese": "Bloons TD 6"},
    "972660": {"schinese": "灵魂旅人®：告别版", "japanese": "Spiritfarer: Farewell Edition"},
    "990080": {"schinese": "霍格沃茨之遗", "japanese": "Hogwarts Legacy"},
    "1009850": {"schinese": "OVR Advanced Settings", "japanese": "OVR Advanced Settings"},
    "1011510": {"schinese": "Wizard And Minion Idle", "japanese": "Wizard And Minion Idle"},
    "1028630": {"schinese": "板球 19", "japanese": "Cricket 19"},
    "1041320": {"schinese": "王国纪元：战争之王", "japanese": "Lords Mobile: Kingdom Wars"},
    "1055010": {"schinese": "Energy Engine PC 动态壁纸", "japanese": "Energy Engine PC Live Wallpaper"},
    "1085510": {"schinese": "加菲猫赛车 狂飙版", "japanese": "Garfield Kart - Furious Racing"},
    "1085660": {"schinese": "命运 2", "japanese": "Destiny 2"},
    "1086940": {"schinese": "博德之门 3", "japanese": "バルダーズ・ゲート 3"},
    "1091500": {"schinese": "赛博朋克 2077", "japanese": "Cyberpunk 2077"},
    "1100600": {"schinese": "足球经理 2020", "japanese": "Football Manager 2020"},
    "1118200": {"schinese": "People Playground", "japanese": "People Playground"},
    "1118310": {"schinese": "RetroArch", "japanese": "RetroArch"},
    "1127400": {"schinese": "工业时代", "japanese": "Mindustry"},
    "1147690": {"schinese": "NGU IDLE", "japanese": "NGU IDLE"},
    "1161490": {"schinese": "MotoGP™20", "japanese": "MotoGP 20"},
    "1172310": {"schinese": "蒙娜丽莎：超越玻璃", "japanese": "Mona Lisa: Beyond The Glass"},
    "1172470": {"schinese": "Apex 英雄™", "japanese": "Apex Legends"},
    "1190000": {"schinese": "汽车修理工模拟器 2021", "japanese": "Car Mechanic Simulator 2021"},
    "1204050": {"schinese": "Pixel Studio - 像素画编辑器", "japanese": "Pixel Studio - pixel art editor"},
    "1210320": {"schinese": "药剂工艺：炼金术士模拟器", "japanese": "Potion Craft: Alchemist Simulator"},
    "1213210": {"schinese": "命令与征服™ 重制版 合集", "japanese": "コマンド＆コンカー リマスター"},
    "1222140": {"schinese": "底特律：化身为人", "japanese": "Detroit: Become Human"},
    "1237970": {"schinese": "泰坦陨落® 2", "japanese": "Titanfall 2"},
    "1244800": {"schinese": "Terraformers", "japanese": "Terraformers"},
    "1245620": {"schinese": "艾尔登法环", "japanese": "ELDEN RING"},
    "1263850": {"schinese": "足球经理 2021", "japanese": "Football Manager 2021"},
    "1283970": {"schinese": "YoloMouse - 游戏光标更换器", "japanese": "YoloMouse - Game Cursor Changer"},
    "1286830": {"schinese": "星球大战™：旧共和国™", "japanese": "STAR WARS: The Old Republic"},
    "1292940": {"schinese": "逃离方块合集", "japanese": "Cube Escape Collection"},
    "1326470": {"schinese": "森林之子", "japanese": "Sons Of The Forest"},
    "1337970": {"schinese": "CatTuber", "japanese": "CatTuber"},
    "1366800": {"schinese": "Crosshair X", "japanese": "Crosshair X"},
    "1374480": {"schinese": "爱人 Lover", "japanese": "愛人 Lover"},
    "1424330": {"schinese": "Wobbledogs", "japanese": "Wobbledogs"},
    "1454400": {"schinese": "饼干点击器", "japanese": "Cookie Clicker"},
    "1466860": {"schinese": "帝国时代 IV 周年纪念版", "japanese": "Age of Empires IV: Anniversary Edition"},
    "1480140": {"schinese": "RPG Sounds", "japanese": "RPG Sounds"},
    "1486350": {"schinese": "VRoid Studio v2.7.0", "japanese": "VRoid Studio v2.7.0"},
    "1491670": {"schinese": "Venba", "japanese": "Venba"},
    "1545560": {"schinese": "暗影诡计：被诅咒的船员", "japanese": "Shadow Gambit: The Cursed Crew"},
    "1546570": {"schinese": "仙剑奇侠传七", "japanese": "仙剣奇侠伝七"},
    "1569040": {"schinese": "足球经理 2022", "japanese": "Football Manager 2022"},
    "1599340": {"schinese": "失落的方舟", "japanese": "ロストアーク"},
    "1605010": {"schinese": "可爱的女巫", "japanese": "Adorable Witch"},
    "1623730": {"schinese": "幻兽帕鲁", "japanese": "Palworld"},
    "1625080": {"schinese": "做个好梦", "japanese": "Have a Nice Dream"},
    "1637370": {"schinese": "Letters From a Rainy Day -Oceans and Lace-", "japanese": "Letters From a Rainy Day -Oceans and Lace-"},
    "1650010": {"schinese": "RIDE 5", "japanese": "RIDE 5"},
    "1669980": {"schinese": "火山的女儿", "japanese": "Volcano Princess"},
    "1687950": {"schinese": "女神异闻录 5 皇家版", "japanese": "ペルソナ5 ロイヤル"},
    "1708150": {"schinese": "Juice Galaxy", "japanese": "Juice Galaxy"},
    "1775490": {"schinese": "Slice & Dice", "japanese": "Slice & Dice"},
    "1787090": {"schinese": "MyDockFinder", "japanese": "MyDockFinder"},
    "1794680": {"schinese": "吸血鬼幸存者", "japanese": "Vampire Survivors"},
    "1844610": {"schinese": "Reality Mixer", "japanese": "Reality Mixer - Mixed Reality for VR headsets"},
    "1849570": {"schinese": "Love Stories: When Pastel Meets Grotesque", "japanese": "Love Stories: When Pastel Meets Grotesque"},
    "1893620": {"schinese": "Circadian Dice", "japanese": "Circadian Dice"},
    "1901340": {"schinese": "Ero Manager", "japanese": "Ero Manager"},
    "1904540": {"schinese": "足球经理 2023", "japanese": "Football Manager 2023"},
    "1934680": {"schinese": "神话时代：重述", "japanese": "Age of Mythology: Retold"},
    "1938090": {"schinese": "使命召唤®", "japanese": "コール オブ デューティ"},
    "1943950": {"schinese": "逃离后室", "japanese": "Escape the Backrooms"},
    "1966720": {"schinese": "致命公司", "japanese": "Lethal Company"},
    "2073470": {"schinese": "Kanjozoku Game レーサー", "japanese": "Kanjozoku Game レーサー Online Street Racing & Drift"},
    "2078450": {"schinese": "战锤 40,000：极速狂飙", "japanese": "Warhammer 40,000: Speed Freeks"},
    "2128270": {"schinese": "Path of Achra", "japanese": "Path of Achra"},
    "2142790": {"schinese": "Fields of Mistria", "japanese": "Fields of Mistria"},
    "2252570": {"schinese": "足球经理 2024", "japanese": "Football Manager 2024"},
    "2358720": {"schinese": "黑神话：悟空", "japanese": "Black Myth: Wukong"},
    "2386460": {"schinese": "Tree It", "japanese": "Tree It"},
    "2395210": {"schinese": "托尼·霍克™ 滑板™ 1 + 2", "japanese": "Tony Hawk's Pro Skater 1 + 2"},
    "2427700": {"schinese": "背包乱斗", "japanese": "Backpack Battles"},
    "2536840": {"schinese": "GINKA", "japanese": "GINKA"},
    "2593370": {"schinese": "饿狼：晚明之旅", "japanese": "The Hungry Lamb: Traveling in the Late Ming Dynasty"},
    "2660460": {"schinese": "Aviassembly", "japanese": "Aviassembly"},
    "2670630": {"schinese": "超市模拟器", "japanese": "Supermarket Simulator"},
    "2707900": {"schinese": "NIGHT-RUNNERS™ 序章", "japanese": "NIGHT-RUNNERS PROLOGUE"},
    "2784470": {"schinese": "9 Kings", "japanese": "9 Kings"},
    "2881650": {"schinese": "内容警告", "japanese": "Content Warning"},
    "3029820": {"schinese": "Ai Vpet", "japanese": "Ai Vpet"},
    "3070070": {"schinese": "TCG 卡牌店模拟器", "japanese": "TCG Card Shop Simulator"},
    "3164500": {"schinese": "Schedule I", "japanese": "Schedule I"},
    "3241660": {"schinese": "R.E.P.O.", "japanese": "R.E.P.O."},
    "3449850": {"schinese": "桌面猫娘", "japanese": "Desktop Kitten Girl"},
}

# 验证：从 timeline_data.json 提取需要的 appid，确认覆盖
with open("timeline_data.json", "r", encoding="utf-8") as f:
    data = json.load(f)

needed = set()
for y, yd in data["yearly"].items():
    for g in yd.get("top5", []):
        if g.get("appid"):
            needed.add(str(g["appid"]))
    for g in yd.get("best_by_genre", []):
        if g.get("appid"):
            needed.add(str(g["appid"]))
    top1 = yd.get("top1_appid")
    if top1:
        needed.add(str(top1))

covered = needed & set(GAME_NAMES.keys())
missing = needed - set(GAME_NAMES.keys())

print(f"需要翻译: {len(needed)} 个游戏")
print(f"已覆盖: {len(covered)}")
print(f"未覆盖: {len(missing)}")
if missing:
    print(f"\n缺失的游戏 appid:")
    for m in sorted(missing):
        print(f"  {m}")

# 只输出需要的游戏（去掉不在列表中的）
output = {k: v for k, v in GAME_NAMES.items() if k in needed}

with open("game_names.json", "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

sz = len(json.dumps(output, ensure_ascii=False))
print(f"\ngame_names.json 已生成 ({sz // 1024} KB)")
print(f"共 {len(output)} 个游戏条目")
